### ISSUE TITLE
Error for the new version

### ISSUE THREAD

**Issue by Jinjin-Li** [bizzinho/ADDICT_Issues#28] opened 2016-03-14 22:23 UTC
Hello Dave,

ADDICT encountered errors with the new version "Shape_20160314" for both Matlab2013 and Matlab2014.
Here shows the error with Matlab2013:
![1](https://cloud.githubusercontent.com/assets/17035064/13768612/56ee77aa-ea35-11e5-910f-0daf41b85611.png)

Here shows the error with Matlab2014:
![2](https://cloud.githubusercontent.com/assets/17035064/13768660/ed5381d6-ea35-11e5-9cfe-85adc078952b.png)

Thanks

**Comment by bizzinho** [comment] 2016-03-15 05:21
Well. The first error seems to appear because you have a script named plot on the desktop that overrides the default Matlab one... The latter says terminated by use... Did you maybe click ctrl+c?

**Comment by Jinjin-Li** [comment] 2016-03-15 05:46
Hello Dave,
Sorry, I uploaded wrong figures on GitHub. Please see the right figures above and let me know how to fix it.
Thank you.

**Comment by bizzinho** [comment] 2016-03-16 19:36
hmm, ok, I think I understand the 2014 problem... I'm still trying to wrap my head around the other one

**Comment by bizzinho** [comment] 2016-03-17 12:17
ok, I cannot reproduce the 2013 error... the only thing I can think of is that somehow the parameters.txt file was manipulated during the runtime of this ADDICT instance (maybe two ADDICT sessions at the same time?)

please try to rewrite lines 1293 and 1294, which should be

```
fid = fopen('parameters.txt','w');
fprintf(fid,'%s\n',para.ori_name);
```

to the following

```
[fid,msg] = fopen('parameters.txt','w');
try
    fprintf(fid,'%s\n',para.ori_name);
catch
    disp(msg)
end
```

this should tell us the reason why the opening failed.

**Comment by Jinjin-Li** [comment] 2016-03-18 04:20
Hi Dave, after rewroting lines 1293 and 1294, ADDIT works with Matlab2013a (I am using Matlab2013a and Matlab2014a). But ADDICT still doesn't work with Matlab2014a.

For Matlab2013a, there is a small bug, that is, when running the ADIPAC09 with solvent sweep, there is only one point in the morphology map.
![1](https://cloud.githubusercontent.com/assets/17035064/13868414/a967b83c-ec85-11e5-891b-654a3f54a3d0.jpg)

The following figure shows the error with Matlab2014a after rewroting lines 1293 and 1294
![2014](https://cloud.githubusercontent.com/assets/17035064/13868442/02396c26-ec86-11e5-80a2-c5aecfe14c54.png)

**Comment by bizzinho** [comment] 2016-03-18 05:10
Yeah, the change was not supposed to fix the 2014 problem, but I know what it is and have fixed it. However, it also wouldn't have fixed the 2013 problem, just tell us what caused it... If it's not reproducible then I can't debug.

I'll have a look at adipic acid today.

**Comment by bizzinho** [comment] 2016-03-18 11:41
So the problem with adipic acid was that ADDICT wrongly interpreted these morphologies to belong to different morphology maps. As an example: it would see one crystal that had facets 010,101,001 and then another one with 001,101,010... not realizing that just the order was changed (it's a bit more involved than that, but you get the gist).

I've fixed this issue and will send you a new version. In this new version, the Matlab 2014 error should be fixed as well as the adipic acid problem. As for the Matlab 2013 issue (the fid error), if we don't get it again I assume it was a fluke because of a txt file that was accessed by another program simultaneously.

**Comment by Jinjin-Li** [comment] 2016-03-18 19:34
Hi Dave, 
      Thanks for sending us the update version of ADDICT. Unitl now, this version works good for Matlab2013 and Matlab 2014. I didn't find any error. I will continue to test it. 
      But I remembered you have told me that the Vary lg(L4/L3) will be replaced by the real crystal indices within Matlab 2014 or Matlab 2015.  Mike prefer to see the crystal indices for this Vary lg(L4/L3). However, I can't see this change with Matlab2014.
![1](https://cloud.githubusercontent.com/assets/17035064/13889636/e026c258-ed04-11e5-8092-09e43b23ba18.png)

Another small bug is: the "?" always appear when change the solvent in the top right corner.
![2](https://cloud.githubusercontent.com/assets/17035064/13889723/4c5ce722-ed05-11e5-8582-d72ac1d40031.png)

Thanks.

**Comment by Jinjin-Li** [comment] 2016-03-19 21:29
On interface, the "Save Current Sate" shoud be changed to "Save Current State". A "t" is missed.

![3](https://cloud.githubusercontent.com/assets/17035064/13901364/bdd38fe4-edde-11e5-8965-bda984813974.png)

**Comment by bizzinho** [comment] 2016-03-22 12:25
lol @typo, I fixed that thanks

regarding L4/L3: ADDICT should show the correct behavior for Matlabs 2014b and higher. Unfortunately, for older Matlab versions my options when it comes to showing text in the middle of a figure are quite restricted. I will check again, but right now I don't see a way around having to write L4/L3 there for these versions.

**Comment by Jinjin-Li** [comment] 2016-03-23 06:10
Hello Dave, I just send you an email with attachment, please check it.
Let's have a talk tomorrow.

**Comment by bizzinho** [comment] 2016-03-23 17:29
I removed the ??? entirely, since the remaining figures are still valid for that compound/solvent combination I thought this would be fair.

**Closed by bizzinho** 2016-03-23 17:29 UTC
