### ISSUE TITLE
Executable version of ADDICT

### ISSUE THREAD

**Issue by Jinjin-Li** [bizzinho/ADDICT_Issues#32] opened 2016-03-23 23:25 UTC
Hi Dave, Some of your morphology files have the name beginning with "." or "@", which are not allowed when generating the executable Matlab version. I think these files may not the required files for ADDICT. Could you let me know the main files and the required files for your morphology map creator? 

When I generated the executable version of ADDICT, there are some errors because of these files:
![k6lf xdr86f8 jebwexeq8w](https://cloud.githubusercontent.com/assets/17035064/14003835/d5561998-f112-11e5-8fcc-e0f5df12d645.png)

**Comment by bizzinho** [comment] 2016-03-24 12:37
Problem is duplicate of #30 and has been solved.

**Closed by bizzinho** 2016-03-24 12:37 UTC
Labels: duplicate
