### ISSUE TITLE
Error #2

### ISSUE THREAD

**Issue by carltilbury** [bizzinho/ADDICT_Issues#2] opened 2016-01-29 22:27 UTC
![error2-1](https://cloud.githubusercontent.com/assets/16385845/12689765/c4399968-c693-11e5-9d92-92ab9317de9b.PNG)
![error2-2](https://cloud.githubusercontent.com/assets/16385845/12689764/c435e9a8-c693-11e5-8e25-b14fd4301e7d.PNG)

Updated to 2015a and got another error.  Again I just selected the CIF file and output path, then clicked run.  The crystal shape and log output tabs are the only ones populated and I don't get a morphology map.

**Comment by bizzinho** [comment] 2016-01-30 11:48
Can you send me the cif file tat you have used?

**Comment by bizzinho** [comment] 2016-02-01 15:06
Ok I identified and fixed the problem in the new patch.

**PLEASE BE AWARE OF THE FOLLOWING:**
Right now, I have decided that the morphology map will be created _as if_ all facets growing faster than the fourth fastest growing facet group (let's call them G4+) do not exist. Consequently, it can happen that when dragging around the point in the map the morphology appears to change (G4+ appear or disappear) even though you do not cross a boundary of the morphology domain_. The reason for this is that during dragging, the aspect ratio between G4+ and G4 is assumed constant, while I cannot do the same in the morphology map calculation (due to the way the algorithm works). This is particularly obvious far away from the origin of the 2D map and for slider positions far to the left (essentially, when originally slow-growing facets start to disappear). I consider this a minor issue because I think this is a very infrequent event in real life.

**ANYHOW, IF THIS IS UNACCEPTABLE FOR YOU**
Unfortunately, my standard algo becomes a resource hog when moving to dimensions larger than 4 and fixing the aspect ratios does not seem to work reliably. I see only one solution, namely to bruteforce my way through the map for cases when there are more than four independently growing facets. This way I could reliably detect all transitions in morphology, though coloring becomes an issue (see below).

**SUMMARY ADVANTAGES / DISADVANTAGES**
No Bruteforcing:
`+` Faster calculation of maps with higher resolution
`+` Same approach everywhere
`+` Known upper bound number of morphology domains
`-` Unexpected behavior at extreme aspect ratio combinations

Bruteforcing for n>4
`+` No unexpected behavior, ever.
`-` Slower computation of maps, need to reduce resolution of maps for these cases
`-` Number of potential morphology domains is 2^n-1 where n is the number of independently growing facet groups. I would be hardpressed to find enough colors...
`-` Not same approach everywhere...

Please discuss and let me know how I should proceed.

**Comment by carltilbury** [comment] 2016-02-02 03:19
My opinion is to leave it as is and no brute forcing.  I agree it's an unphysical domain that has the error so don't think it's worth the added computational cost to map out that region perfectly.  However, there should probably be some tooltip leading to pages in the manual where this issue is explained in detail.

**Comment by bizzinho** [comment] 2016-02-02 07:01
Will implement in the next patch

**Comment by bizzinho** [comment] 2016-02-08 09:54
This is now implemented as discussed. I have added a warning within the morphology map that appears when this case occurs.

**Closed by bizzinho** 2016-02-08 09:54 UTC
